# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip' 
    - name: Install dependencies
      run: |
        sudo apt update > /dev/null 
        sudo apt-get -q update
        sudo apt-get -q -y install tmux vim libncurses5 fbclient2
        python -m pip -q install -U pip virtualenv flake8 pytest
        if [ -f requirements.txt ]; then pip -q install -r requirements.txt; fi
    - name: Setup lhotari ssh session on disaster
      if: ${{ failure() || success() }} 
      uses: lhotari/action-upterm@v1
