# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip' 
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get update
        sudo apt-get -y install tmux vim libncurses5
        wget https://github.com/FirebirdSQL/firebird/releases/download/R2_5_8/FirebirdCS-2.5.8.27089-0.amd64.tar.gz
        tar xzf FirebirdCS-2.5.8.27089-0.amd64.tar.gz
        cd FirebirdCS-2.5.8.27089-0.amd64
        tar xzf buildroot.tar.gz 
        mv opt/firebird /opt
        python -m pip install --upgrade pip setuptools wheel virtualenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
#    - name: Setup upterm session
#      uses: lhotari/action-upterm@v1
    
    - name: Test with pytest
      run: |
        pytest    

